---
version: '{build}'
shallow_clone: true
environment:
  matrix:
  - CPU: i386
    ENV: /x86
    BIT: 32
  - CPU: AMD64
    ENV: /x64
    BIT: 64
install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" %ENV%'
  - curl http://files.kaoriya.net/vim/vim74-kaoriya-win%BIT%.zip -s -o vim.zip
  - unzip -q vim.zip
  - git clone -q https://github.com/thinca/vim-themis.git themis --depth=1
  - set THEMIS_VIM=%APPVEYOR_BUILD_FOLDER%\vim74-kaoriya-win%BIT%\vim.exe
build_script:
  - nmake -f make_msvc.mak nodebug=1 CPU=%CPU%
test_script:
  - themis\bin\themis
artifacts:
  - path: autoload/vimproc_*.dll
    name: vimproc.dll
deploy:
  provider: GitHub
  description: vimproc
  auth_token:
    secure: rKd6JLXUIl3vcA8d0S9w14bl+uvUlZLt0d1M8bmlOh+owQqr5c40+/4ITCNBpHG3
  on:
    appveyor_repo_tag: true
